Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - db/*
    - config/*
    
Layout/LineLength:
  Exclude:
    - 'lib/tasks/import_nacebel_codes.rake'

AllCops:
  NewCops: enable
  Exclude:
    - db/**/*
    - config/**/*
    - node_modules/**/*
    - config.ru
    - bin/*
    - Guardfile

Metrics/MethodLength:
  Max: 15
  CountAsOne: ['array', 'hash']